language: go
sudo: required
dist: trusty

matrix:
  include:
    - go: 1.6

install:
  - mkdir -p $HOME/gopath/src/k8s.io
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/k8s.io/frakti
  - go install -v $(go list ./... | grep -v /vendor/)
  - ./hack/verify-all.sh

script:
  - cd $HOME/gopath/src/k8s.io/frakti
  - hack/test-go.sh
