language: go
sudo: required
dist: xenial

services:
  - docker

env:  
    global:
        - DOCKER_VERSION=17.03.2~ce-0~ubuntu-xenial

go:
  - 1.9.x

go_import_path: k8s.io/frakti

script:  
    - docker version

install:
  - hack/verify-all.sh -v

jobs:
   include:
     - stage: Unit Test
       script: hack/test-go.sh
     - stage: End to End Test
       script: hack/test-e2e.sh

